name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push Data to Server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./build/*
          remote_path: /home/react_app
          remote_host: ${{ secrets.BACKEND_SERVER_HOST }}
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}